services:
  - type: web
    name: global-chat-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    rootDir: .
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: APPLICATION_ID
        sync: false
